Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 30, in add_messages
    result = reply_message(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 128, in reply_message
    return jsonify(result_json)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Response 3 bytes [200 OK]> is not JSON serializable
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 30, in add_messages
    result = reply_message(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 129, in reply_message
    return jsonify(result_json)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Response 3 bytes [200 OK]> is not JSON serializable
Exception on /messages/ [POST]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 30, in add_messages
    result = reply_message(content)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\message.py", line 129, in reply_message
    return jsonify(result_json)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 321, in jsonify
    dumps(data, indent=indent, separators=separators) + '\n',
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 179, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\json\__init__.py", line 81, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Response 3 bytes [200 OK]> is not JSON serializable
Exception on /notifications [GET]
Traceback (most recent call last):
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\devuri\workspace\server\venv352\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\devuri\workspace\server\DajeongBot-server\djbot\blueprints\test.py", line 101, in notification
    push_service.notify_single_device(registration_id=token, data_message=param, content_available=True)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\pyfcm\fcm.py", line 94, in notify_single_device
    **extra_kwargs)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\pyfcm\baseapi.py", line 203, in parse_payload
    return self.json_dumps(fcm_payload)
  File "D:\devuri\workspace\server\venv352\lib\site-packages\pyfcm\baseapi.py", line 71, in json_dumps
    return (json.dumps(data, separators=(',', ':'), sort_keys=True, cls=self.json_encoder)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "c:\users\hanyuri\appdata\local\programs\python\python35\Lib\json\encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Event 16> is not JSON serializable
